from enum import IntEnum


class GameMode(IntEnum):
    NONE = 0
    ALL_PICK = 1
    CAPTAINS_MODE = 2
    RANDOM_DRAFT = 3
    SINGLE_DRAFT = 4
    ALL_RANDOM = 5
    INTRO = 6
    DIRETIDE = 7
    REVERSE_CAPTAINS_MODE = 8
    THE_GREEVILING = 9
    TUTORIAL = 10
    MID_ONLY = 11
    LEAST_PLAYED = 12
    NEW_PLAYER_POOL = 13
    COMPENDIUM_MATCHMAKING = 14
    COOP_VS_BOTS = 15
    CAPTAINS_DRAFT = 16
    ABILITY_DRAFT = 18
    ALL_RANDOM_DEATHMATCH = 20
    OVO_MID_ONLY = 21
    RANKED_MATCHMAKING = 22
    TURBO = 23
